Add javadocs
DroidsOnRoids/Casty pull request #1
Opened 2017-03-27 18:52 UTC by burnoo

2017-03-27 22:19 UTC, koral-- requested changes

2017-03-27 22:19 UTC, koral-- commented on casty/src/main/java/pl/droidsonroids/casty/Casty.java
> +     * @param activity Activity in which Casty object is created
missing link

2017-03-27 22:19 UTC, koral-- commented on casty/src/main/java/pl/droidsonroids/casty/Casty.java
> +     * @return the instance of {@link CastyPlayer}
code instead of link should be better

2017-03-27 22:19 UTC, koral-- commented on casty/src/main/java/pl/droidsonroids/casty/Casty.java
> +     * Checks if a Google Cast device is connected
There should be dot at the end of sentence.

2017-03-27 22:19 UTC, koral-- commented on casty/src/main/java/pl/droidsonroids/casty/Casty.java
> +     * Adds the Mini Controller at the bottom of Activity's layout
missing info about UI thread

2017-03-27 22:19 UTC, koral-- commented on casty/src/main/java/pl/droidsonroids/casty/MediaData.java
> +         * @return Builder instance
this instance to/for chain calls

2017-03-28 06:43 UTC, burnoo commented on casty/src/main/java/pl/droidsonroids/casty/Casty.java
> +     * @return the instance of {@link CastyPlayer}
Why?

2017-03-28 11:09 UTC, koral-- approved these changes

2017-03-28 11:11 UTC, merged